### PR TITLE
GitHub API compliant

### PR DESCRIPTION
**Pull request by JacobMGEvans**
changed the handling of inputs to not conflict with GitHub API and removed documentation reflecting that.

### CODE REVIEW

**Review by Ilshidur — APPROVED** [review]
Looks good to me.

**Comment by Ilshidur** [comment]
Hello Jacob. Thanks for your contribution. This is actually a better way to handle this parameter.

Merging.

**Comment by Ilshidur** [comment]
After further testing, I noticed that calling the [`POST/webhooks/{webhook.id}/{webhook.token}/github` Discord endpoint](https://discord.com/developers/docs/resources/webhook#execute-githubcompatible-webhook) with the body sent by this action doesn't work, as this endpoint only accepts a specific body format that is sent by GitHub.

The request bodies used by those 2 routes are different :
* [`POST/webhooks/{webhook.id}/{webhook.token}`](https://discord.com/developers/docs/resources/webhook#execute-githubcompatible-webhook)
* [`POST/webhooks/{webhook.id}/{webhook.token}/github`](https://discord.com/developers/docs/resources/webhook#execute-githubcompatible-webhook)

I tried to make the Action send a [GitHub webhook event](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads) to the **/github** endpoint with no success. The request is accepted but no message is sent on Discord.

I will need to revert the changes until I find a way to adapt the request body according to the targeted Webhook endpoint.
My apologies.

**Comment by JacobMGEvans** [comment]
Darn! I didn't check for that. Appreciate the attempt to merge though, I'll think about it more.

**Pull request merged**
